FROM pytorch/pytorch

WORKDIR /app
ADD models/ models/
ADD module/ module/
ADD preprocess/ preprocess/
ADD samples/ samples/
ADD saved/ShallowCNN_mfcc_O/ saved/ShallowCNN_mfcc_O/
COPY analyze.py DataLoader.py metrics.py train.py trainer.py utils.py requirements.txt ./
COPY entrypoints/entrypoint-ShallowCNN_mfcc_O.py entrypoint.py

RUN python3 -m pip install -U pip wheel setuptools --no-cache-dir && \
    python3 -m pip install torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116 && \
    python3 -m pip install -r requirements.txt --no-cache-dir

CMD [ "uvicorn", "entrypoint:app", "--host", "0.0.0.0", "--port", "50503", "--reload"]